### ISSUE TITLE
Doesn't evaluate expressions

### ISSUE THREAD

**Issue by adam-lynch** [patiernom/gulp-less-json-variables#1]
This a handy idea but it doesn't cover my use case. I have two variables in my JavaScript file;

``` javascript
module.exports = {a: '300px', b: 1.5};
```

Then the LESS uses them and multiples them together and uses them in a media query. 

`a.less`:

``` LESS
@c: @a * @b;
```

`b.less`:

``` LESS
@import "a";
@media (min-width: (@c)) {
// ...
```

Instead of the result being `@media (min-width: (450px)) {`, it's `@media (min-width: (300px * 1.5)) {`.

**Comment by patiernom** [comment]
Hi,
Sorry if I answer only now, but have been busy days. 
I didn't understand clearly your example, in the sense that I would use directly the JSON file with the variables a and b, if the javascript file is static.

But if is a result of your code execution, for example you can do this:

``` javascript
module.export = {
          createVariable: function(){
             ....

            return {
               '@a': '300px', 
               '@b': 1.5
            }
          }
}

...

var gulp = require('gulp'), 
    lessVars = require('gulp-less-json-variables'),
    yourModule= require('yourmodule.js');

gulp.task('generate less variables', function() {
  return gulp.src('less/**/*.less')
    .pipe(lessVars(yourModule.createVariable()))
    .pipe(gulp.dest('dist'));
});
```
